### ISSUE TITLE
Action detected downgrade incorrectly

### ISSUE THREAD

**Issue by wbgneto** [Simek/yarn-lock-changes#38]
![image](https://user-images.githubusercontent.com/1367578/130119587-3779e6ed-268f-485c-a74f-f2b41f4de104.png)

![image](https://user-images.githubusercontent.com/1367578/130119688-4f3f282a-f46f-4977-b541-97600db713d8.png)

Seems it got confused with this diff and incorrectly added date-fns as a downgrade.

**Comment by Simek** [comment]
Hi @wbgneto, thank you for the report! 👍 

The issue should be fixed now, if you are using `main` as version the changes will be visible on the next action run, if you are using the version tag, please updated the action in workflow to version `0.8.1`.

If you are seeing a regression or the invalid downgrade detection problem is not completely fixed in your case, feel free to open new issue. 🙂
